# Generated by Django 6.0.6 on 2026-06-19 13:06

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        # The pgvector extension must exist before this VectorField column is created.
        ("jobs", "0001_enable_pgvector"),
    ]

    operations = [
        migrations.CreateModel(
            name="Resume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("content_hash", models.CharField(db_index=True, max_length=64, unique=True)),
                ("raw_text", models.TextField()),
                ("hard_skills", models.JSONField(default=list)),
                ("soft_skills", models.JSONField(default=list)),
                ("seniority", models.CharField(blank=True, max_length=32)),
                ("years_experience", models.IntegerField(blank=True, null=True)),
                ("titles", models.JSONField(default=list)),
                ("embedding", pgvector.django.vector.VectorField(dimensions=1536)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
